# Test your FastAPI endpoints

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

POST http://127.0.0.1:8000/users/?nickname=${nickname}
Accept: application/json

###

GET http://127.0.0.1:8000/games/game_name/players
Accept: application/json
